spring:
  h2:
    console.enabled: true
  datasource:
    url: jdbc:h2:mem:db
    username: sa
    password: sa
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  mustache:
    check-template-location: 'false'
  liquibase:
    enabled: true
    change-log: classpath:db/db.changelog-master.yaml
vaadin:
  whitelisted-packages: com.vaadin,org.vaadin,dev.hilla,com.example.application
logging:
  level:
    org:
      atmosphere: warn
server:
  port: ${PORT:8080}
